# Jekyll 블로그 설정
title: "김준희의 개발 블로그"
description: "개발과 기술에 대한 이야기를 나누는 공간입니다. 최신 웹 기술, 프로그래밍 팁, 그리고 개발 경험을 공유합니다."
baseurl: "/blog" # GitHub Pages에서 저장소 이름이 username.github.io가 아닌 경우 "/repository-name"
url: "https://wnsgml7838.github.io" # GitHub Pages URL로 변경하세요

# 작성자 정보
author:
  name: "김준희"
  email: "wnsgml7838@naver.com"
  github: "wnsgml7838"

# 빌드 설정
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/

# Jekyll 플러그인 (GitHub Pages 지원)
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-paginate
  - jekyll-minifier

# SEO 최적화
timezone: Asia/Seoul
lang: ko_KR

# Google Search Console
google_site_verification: "your-google-verification-code"

# Bing Webmaster Tools  
bing_site_verification: "your-bing-verification-code"

# Naver Search Advisor
naver_site_verification: "your-naver-verification-code"

# SEO 메타 태그 설정
seo_meta:
  title: "김준희의 개발 블로그 - 최신 웹 기술과 프로그래밍 이야기"
  description: "개발과 기술에 대한 깊이 있는 이야기를 나누는 공간입니다. React, Node.js, Python 등 최신 웹 기술과 프로그래밍 팁, 개발 경험을 공유합니다."
  keywords: "웹개발, 프로그래밍, React, JavaScript, Node.js, Python, 기술블로그, 개발자, 튜토리얼"
  image: "/assets/images/og-image.jpg"
  
# JSON-LD 구조화 데이터
structured_data:
  organization:
    name: "김준희의 개발 블로그"
    url: "https://wnsgml7838.github.io/blog/"
    logo: "/assets/images/logo.png"
    same_as:
      - "https://github.com/wnsgml7838"
  person:
    name: "김준희"
    job_title: "웹 개발자"
    url: "https://github.com/wnsgml7838"

# 성능 최적화
sass:
  style: compressed
  sourcemap: never

# 압축 설정 (GitHub Pages에서 자동 처리됨)
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  startings: [html, head, body]
  blanklines: false
  profile: false
  ignore:
    envs: [development]

# Jekyll 빌드 성능 최적화
incremental: true
profile: false
strict_front_matter: true
liquid:
  error_mode: strict
  strict_filters: true
  strict_variables: false

# 캐싱 설정
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# 페이지네이션
paginate: 10
paginate_path: "/page:num/"

# 제외할 파일
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md

# 기본 레이아웃
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

# 테마 설정
theme: minima

# 소셜 미디어 링크
social_links:
  github: wnsgml7838
  twitter: 
  linkedin:

# 기술 블로그 설정
tech_blog:
  # 읽기 시간 계산 (단어당 분)
  reading_speed: 200  # 분당 200단어
  # 코드 하이라이팅 설정
  code_highlighting:
    line_numbers: true
    copy_button: true
    language_badges: true
  # 튜토리얼 설정
  tutorial:
    progress_tracking: true
    completion_rewards: true
  # API 문서 설정
  api_docs:
    expand_examples: true
    interactive_try: false